# Generated by Django 5.2.5 on 2025-08-31 06:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('stock_no', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mileage', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('semi-automatic', 'Semi-Automatic')], max_length=20)),
                ('fuel', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=20)),
                ('warranty', models.CharField(default='Under Warranty', max_length=100)),
                ('spec', models.CharField(default='GCC Specs', max_length=100)),
                ('cylinders', models.PositiveIntegerField()),
                ('body_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('pickup', 'Pickup'), ('van', 'Van'), ('other', 'Other')], max_length=50)),
                ('about', models.TextField(blank=True, null=True)),
                ('key_features', models.TextField(help_text='Enter one feature per line.')),
                ('main_image', models.ImageField(upload_to='cars/main_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='cars.car')),
            ],
        ),
    ]
