# Generated by Django 5.2.5 on 2025-09-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='bmw'),
            preserve_default=False,
        ),
    ]
