# Generated by Django 5.2.5 on 2025-09-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_available_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='main_image',
            field=models.ImageField(upload_to='cars/main/'),
        ),
    ]
