# Generated by Django 5.2.5 on 2025-09-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='down_pay',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='full_price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
