# Generated by Django 5.2.5 on 2025-09-02 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0004_alter_car_down_pay_alter_car_full_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('car_name', models.CharField(max_length=255)),
                ('car_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_year', models.PositiveIntegerField()),
                ('car_model', models.CharField(max_length=255)),
                ('stock_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cars.car')),
            ],
        ),
    ]
